# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b938a44bd74abff8e168206618c663ce0892ad317addbbdd53ef3af47fca7b44d5df1c7713540cdd67ce4d82381e02d3051c2a196d7219af574c482f04a7766

test:
  secret_key_base: 054d88294e2858088a9357ffa3589b1a35183ee1d722338d1d71d1b54a638193f75870fc8e66d002649fd7bb389308a21cd818784b2f66ef2da62a748a884935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
